"""Tests for the MP-M1 verified modeling-trace generator (mixle_pde.verification.modeling_traces).

Every trace under test is generated by actually invoking the real, unmodified ``elastic-fd-leapfrog``
kernel registered in ``mixle_pde.pde_backend_registry`` (not a mock), so these tests double as the
"not fabricated" proof the module's own docstring requires: they assert the trace's labels against
the *raw* ``PDEStudyResult.evidence`` the real kernel actually returned, not merely against the
generator's own internal bookkeeping.
"""

from __future__ import annotations

import math

import pytest

from mixle_pde.verification.modeling_traces import (
    GENERATOR_ID,
    GENERATOR_VERSION,
    ModelingStepKind,
    ModelingTrace,
    ModelingTraceOutcome,
    generate_elastic_cfl_trace,
    generate_elastic_cfl_trace_corpus,
    generate_elastic_cfl_unresolved_trace,
)

torch = pytest.importorskip("torch", reason="elastic-fd-leapfrog uses the differentiable ops backend")

_COURANT_LIMIT = 1.0 / math.sqrt(3.0)
_STEP_KIND_SEQUENCE = (
    ModelingStepKind.REQUIREMENT,
    ModelingStepKind.ASSUMPTION,
    ModelingStepKind.CHECK,
    ModelingStepKind.OUTCOME,
    ModelingStepKind.REPAIR,
    ModelingStepKind.CHECK,
    ModelingStepKind.OUTCOME,
)


# ---------------------------------------------------------------------------
# Determinism (mirrors DISC-T2's "regenerated items have identical typed hashes" gate)
# ---------------------------------------------------------------------------
def test_generate_elastic_cfl_trace_is_deterministic_given_a_seed():
    first = generate_elastic_cfl_trace(seed=42)
    second = generate_elastic_cfl_trace(seed=42)
    assert first.trace_id == second.trace_id
    assert first.trace_digest == second.trace_digest
    assert first.violating_problem == second.violating_problem
    assert first.repaired_problem == second.repaired_problem


def test_different_item_index_produces_a_different_trace():
    first = generate_elastic_cfl_trace(seed=42, item_index=0)
    second = generate_elastic_cfl_trace(seed=42, item_index=1)
    assert first.trace_id != second.trace_id
    assert first.trace_digest != second.trace_digest


def test_generator_identity_is_recorded_on_every_trace():
    trace = generate_elastic_cfl_trace(seed=1)
    assert trace.generator_id == GENERATOR_ID
    assert trace.generator_version == GENERATOR_VERSION
    assert trace.backend_id == "elastic-fd-leapfrog"
    assert trace.kernel_source == "mixle_pde.elastic.ElasticWave3D"


# ---------------------------------------------------------------------------
# Structural shape: requirement -> assumption -> check -> outcome -> repair -> check -> outcome
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("seed", [0, 1, 2, 7])
def test_trace_steps_follow_the_requirement_assumption_check_outcome_repair_sequence(seed):
    trace = generate_elastic_cfl_trace(seed=seed)
    assert tuple(step.kind for step in trace.steps) == _STEP_KIND_SEQUENCE
    assert all(step.statement.strip() for step in trace.steps)


# ---------------------------------------------------------------------------
# The "detect" step is a genuine failure against the real kernel's own return value, not fabricated.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("seed", [0, 1, 2, 7])
def test_violating_run_is_a_genuine_precondition_violation(seed):
    trace = generate_elastic_cfl_trace(seed=seed)

    # This module's own a-priori recomputation (before the kernel ever ran) really did exceed the limit.
    assert trace.violating_verification.predicted_violates_limit is True
    assert trace.violating_verification.predicted_courant_number > _COURANT_LIMIT

    # The real kernel's own actual returned evidence agrees -- this is not this module's opinion.
    assert trace.violating_evidence["convergence"]["stable"] is False
    assert trace.violating_verification.agrees_with_kernel_report is True
    assert trace.detected_failure_class in ("cfl_violation_diverged", "cfl_violation_unstable_growth")

    # The independent recheck of the raw returned array is consistent with the recorded failure class.
    if trace.detected_failure_class == "cfl_violation_diverged":
        assert trace.violating_verification.raw_solution_finite is False
    else:
        assert trace.violating_verification.raw_solution_finite is True


# ---------------------------------------------------------------------------
# The repair is genuinely re-verified against the real kernel's second (repaired) run.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("seed", [0, 1, 2, 7])
def test_repaired_run_is_independently_confirmed_healthy(seed):
    trace = generate_elastic_cfl_trace(seed=seed)

    assert trace.final_outcome is ModelingTraceOutcome.REPAIRED
    assert trace.final_failure_class is None

    # Independent recomputation (not the evidence dict) says the repaired parameters satisfy the limit.
    assert trace.repaired_verification.predicted_violates_limit is False
    assert trace.repaired_verification.predicted_courant_number <= _COURANT_LIMIT
    assert trace.repaired_verification.raw_solution_finite is True

    # And the real kernel's own actual return value agrees.
    assert trace.repaired_evidence["convergence"]["stable"] is True
    assert trace.repaired_evidence["convergence"]["finite"] is True
    assert trace.repaired_verification.agrees_with_kernel_report is True

    # The repaired dt is strictly smaller than the violating dt (a real correction, not a no-op).
    assert (
        trace.repaired_problem["solve_plan"]["parameters"]["dt"]
        < (trace.violating_problem["solve_plan"]["parameters"]["dt"])
    )


# ---------------------------------------------------------------------------
# Counterexample path: a real, unmodified second kernel run that is still unstable.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("seed", [0, 1, 2, 7])
def test_unresolved_trace_is_a_genuine_counterexample_not_a_mocked_failure(seed):
    trace = generate_elastic_cfl_unresolved_trace(seed=seed)

    assert tuple(step.kind for step in trace.steps) == _STEP_KIND_SEQUENCE
    assert trace.final_outcome is ModelingTraceOutcome.UNRESOLVED
    assert trace.final_failure_class == "repair_still_violates_precondition"

    # The "repair" attempt is real (dt did change) but insufficient -- independently confirmed still
    # over the limit, and the real kernel's own second run agrees; failed traces are labeled, not dropped.
    assert trace.repaired_verification.predicted_violates_limit is True
    assert trace.repaired_evidence["convergence"]["stable"] is False
    assert trace.repaired_verification.agrees_with_kernel_report is True
    assert (
        trace.repaired_problem["solve_plan"]["parameters"]["dt"]
        != (trace.violating_problem["solve_plan"]["parameters"]["dt"])
    )


def test_repaired_and_unresolved_paths_disagree_only_in_repair_margin():
    repaired = generate_elastic_cfl_trace(seed=3)
    unresolved = generate_elastic_cfl_unresolved_trace(seed=3)
    # Same violating (first) run parameters -- both start from the identical detected failure.
    assert repaired.violating_problem == unresolved.violating_problem
    assert repaired.detected_failure_class == unresolved.detected_failure_class
    # They diverge only once the two different repair margins are applied.
    assert repaired.final_outcome is ModelingTraceOutcome.REPAIRED
    assert unresolved.final_outcome is ModelingTraceOutcome.UNRESOLVED


# ---------------------------------------------------------------------------
# Corpus generation
# ---------------------------------------------------------------------------
def test_generate_elastic_cfl_trace_corpus_produces_n_reproducible_distinct_traces():
    first = generate_elastic_cfl_trace_corpus(seed=5, count=3)
    second = generate_elastic_cfl_trace_corpus(seed=5, count=3)
    assert len(first) == 3
    assert [t.trace_digest for t in first] == [t.trace_digest for t in second]
    assert len({t.trace_digest for t in first}) == 3
    assert all(t.final_outcome is ModelingTraceOutcome.REPAIRED for t in first)


def test_generate_elastic_cfl_trace_corpus_rejects_non_positive_count():
    with pytest.raises(ValueError):
        generate_elastic_cfl_trace_corpus(seed=5, count=0)


# ---------------------------------------------------------------------------
# Immutability / typed-outcome discipline
# ---------------------------------------------------------------------------
def test_trace_and_steps_are_frozen_dataclasses():
    trace = generate_elastic_cfl_trace(seed=9)
    with pytest.raises(AttributeError):
        trace.final_outcome = ModelingTraceOutcome.UNKNOWN  # type: ignore[misc]
    with pytest.raises(AttributeError):
        trace.steps[0].statement = "mutated"  # type: ignore[misc]


def test_final_outcome_is_a_typed_enum_not_a_boolean():
    trace = generate_elastic_cfl_trace(seed=9)
    assert isinstance(trace, ModelingTrace)
    assert isinstance(trace.final_outcome, ModelingTraceOutcome)
    assert trace.final_outcome.value in {"repaired", "unresolved", "unknown"}
