"""Model-error (theory-error) term in the likelihood (work-plan A4): mixle_pde.model_error and the
additive ``model_error_cov``/``model_error`` kwargs on ``gaussian_log_likelihood``/``Differential``.

A perfect-forward assumption makes a posterior overconfident whenever the forward operator itself is
mis-specified: the credible interval shrinks around a systematically biased estimate instead of
widening to admit the theory is imperfect. The tests below demonstrate the failure and the fix. The
headline scenario (``DifferentialModelErrorCoverageTestCase``) fits an ODE decay rate against data
generated by a forward model with a known, unmodeled forcing term (a mis-specified operator): scoring
held-out points against the noise-only budget yields poor coverage, sized ``model_error`` restores it.
"""

import unittest

import numpy as np

from mixle_pde.model_error import diagonal_discrepancy, inflated_noise_cov
from mixle_pde.observations import Observation, gaussian_log_likelihood

try:
    import torch  # noqa: F401

    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

if HAS_TORCH:
    from mixle.ppl import free, joint

    from mixle_pde import Differential
    from mixle_pde.ops import make_ops


class DiagonalDiscrepancyTestCase(unittest.TestCase):
    def test_variances_are_sigma_squared(self):
        d = diagonal_discrepancy(5, 0.3)
        self.assertEqual(d.shape, (5,))
        np.testing.assert_allclose(d, np.full(5, 0.09))

    def test_zero_sigma_is_allowed(self):
        np.testing.assert_allclose(diagonal_discrepancy(3, 0.0), np.zeros(3))

    def test_rejects_bad_input(self):
        with self.assertRaises(ValueError):
            diagonal_discrepancy(0, 0.1)
        with self.assertRaises(ValueError):
            diagonal_discrepancy(3, -0.1)


class InflatedNoiseCovTestCase(unittest.TestCase):
    def test_diagonal_plus_diagonal_stays_diagonal(self):
        r = np.array([0.04, 0.09, 0.16])
        r_model = np.array([0.01, 0.01, 0.01])
        total = inflated_noise_cov(r, r_model)
        self.assertEqual(total.ndim, 1)
        np.testing.assert_allclose(total, r + r_model)

    def test_full_plus_diagonal_promotes_to_full(self):
        r = np.array([[0.04, 0.01], [0.01, 0.09]])
        r_model = np.array([0.02, 0.02])
        total = inflated_noise_cov(r, r_model)
        self.assertEqual(total.shape, (2, 2))
        np.testing.assert_allclose(total, r + np.diag(r_model))

    def test_diagonal_plus_full_promotes_to_full(self):
        r = np.array([0.04, 0.09])
        r_model = np.array([[0.02, 0.005], [0.005, 0.02]])
        total = inflated_noise_cov(r, r_model)
        np.testing.assert_allclose(total, np.diag(r) + r_model)

    def test_shape_mismatch_raises(self):
        with self.assertRaises(ValueError):
            inflated_noise_cov(np.array([0.04, 0.09]), np.array([0.01, 0.01, 0.01]))


class GaussianLogLikelihoodModelErrorTestCase(unittest.TestCase):
    def _obs(self, noise_cov):
        return Observation(kind="test", location=np.zeros((3, 3)), value=np.array([1.0, 2.0, 3.0]), noise_cov=noise_cov)

    def test_default_none_matches_todays_result(self):
        obs = self._obs(np.array([0.04, 0.04, 0.04]))
        predicted = np.array([1.1, 1.9, 3.2])
        baseline = gaussian_log_likelihood(obs, predicted)
        self.assertEqual(gaussian_log_likelihood(obs, predicted, model_error_cov=None), baseline)

    def test_diagonal_model_error_matches_manual_inflation(self):
        noise_cov = np.array([0.04, 0.04, 0.04])
        model_error_cov = diagonal_discrepancy(3, 0.1)
        obs = self._obs(noise_cov)
        predicted = np.array([1.1, 1.9, 3.2])
        got = gaussian_log_likelihood(obs, predicted, model_error_cov=model_error_cov)
        residual = obs.value - predicted
        total = noise_cov + model_error_cov
        expected = float(-0.5 * np.sum(residual**2 / total + np.log(2.0 * np.pi * total)))
        self.assertAlmostEqual(got, expected, places=10)

    def test_model_error_widens_relative_to_no_discrepancy(self):
        # a large residual scores much better once a matching discrepancy is admitted -- an overconfident
        # (noise-only) likelihood punishes a real theory-error bias far more than an inflated one does.
        obs = self._obs(np.array([0.01, 0.01, 0.01]))
        predicted = np.array([1.3, 2.3, 3.3])  # a consistent +0.3 bias, not noise
        naive = gaussian_log_likelihood(obs, predicted)
        inflated = gaussian_log_likelihood(obs, predicted, model_error_cov=diagonal_discrepancy(3, 0.3))
        self.assertGreater(inflated, naive)

    def test_full_model_error_cov_path(self):
        noise_cov = np.array([[0.04, 0.0], [0.0, 0.04]])
        model_error_cov = np.array([[0.01, 0.0], [0.0, 0.01]])
        obs = Observation(kind="test", location=np.zeros((2, 3)), value=np.array([1.0, 2.0]), noise_cov=noise_cov)
        predicted = np.array([1.1, 2.2])
        got = gaussian_log_likelihood(obs, predicted, model_error_cov=model_error_cov)
        total = noise_cov + model_error_cov
        residual = obs.value - predicted
        prec = np.linalg.inv(total)
        _, logdet = np.linalg.slogdet(total)
        expected = float(-0.5 * (residual @ prec @ residual + logdet + 2 * np.log(2.0 * np.pi)))
        self.assertAlmostEqual(got, expected, places=10)


def _sim(rhs, y0, t):
    """Simulate a trajectory with the same integrator the model uses (no discretization mismatch)."""
    ops = make_ops()
    return ops.integrate(rhs, ops.tensor(float(y0)), ops.tensor(t)).detach().numpy()


@unittest.skipUnless(HAS_TORCH, "requires PyTorch")
class DifferentialModelErrorTestCase(unittest.TestCase):
    """``model_error`` is additive and off by default: identical fit to omitting it entirely."""

    def test_default_none_matches_todays_fit(self):
        t = np.linspace(0, 5, 30)
        y = _sim(lambda u, tt: -0.6 * u, 1.0, t) + 0.03 * np.random.RandomState(0).randn(30)
        k1 = free(1, name="k", support="positive")
        obs1 = Differential(y, drivers=[k1], y0=1.0, t_grid=t, scale=0.03, rhs=lambda u, t, p, ops: -p.k * u)
        km1, ks1 = joint([obs1]).fit(how="laplace").posterior("k")

        k2 = free(1, name="k", support="positive")
        obs2 = Differential(
            y, drivers=[k2], y0=1.0, t_grid=t, scale=0.03, rhs=lambda u, t, p, ops: -p.k * u, model_error=None
        )
        km2, ks2 = joint([obs2]).fit(how="laplace").posterior("k")
        self.assertAlmostEqual(km1, km2, places=8)
        self.assertAlmostEqual(ks1, ks2, places=8)

    def test_model_error_rejected_for_poisson(self):
        t = np.linspace(0, 4, 20)
        counts = np.random.RandomState(1).poisson(_sim(lambda u, tt: 0.5 * u, 2.0, t))
        r = free(1, name="r", support="positive")
        with self.assertRaises(ValueError):
            Differential(
                counts,
                drivers=[r],
                y0=2.0,
                t_grid=t,
                family="poisson",
                rhs=lambda u, t, p, ops: p.r * u,
                model_error=0.1,
            )

    def test_model_error_rejects_negative(self):
        t = np.linspace(0, 4, 20)
        y = _sim(lambda u, tt: -0.5 * u, 1.0, t)
        k = free(1, name="k", support="positive")
        with self.assertRaises(ValueError):
            Differential(
                y, drivers=[k], y0=1.0, t_grid=t, scale=0.02, rhs=lambda u, t, p, ops: -p.k * u, model_error=-0.1
            )

    def test_model_error_inflates_posterior_std_without_moving_the_mean(self):
        # inflating the noise budget alone does not move the Gaussian MAP (a constant rescale of every
        # residual leaves the argmax fixed); it should only widen the posterior around it.
        t = np.linspace(0, 5, 30)
        y = _sim(lambda u, tt: -0.6 * u, 1.0, t) + 0.03 * np.random.RandomState(2).randn(30)
        k1 = free(1, name="k", support="positive")
        obs1 = Differential(y, drivers=[k1], y0=1.0, t_grid=t, scale=0.03, rhs=lambda u, t, p, ops: -p.k * u)
        km1, ks1 = joint([obs1]).fit(how="laplace").posterior("k")

        k2 = free(1, name="k", support="positive")
        obs2 = Differential(
            y, drivers=[k2], y0=1.0, t_grid=t, scale=0.03, rhs=lambda u, t, p, ops: -p.k * u, model_error=0.05
        )
        km2, ks2 = joint([obs2]).fit(how="laplace").posterior("k")
        self.assertAlmostEqual(km1, km2, places=6)
        self.assertGreater(ks2, ks1)


@unittest.skipUnless(HAS_TORCH, "requires PyTorch")
class DifferentialModelErrorCoverageTestCase(unittest.TestCase):
    """The Definition-of-Done scenario: a mis-specified operator drives held-out coverage below nominal;
    a ``model_error`` sized to the bias restores it.

    Data is generated by ``dy/dt = -k_true*y - c`` (an unmodeled constant forcing/leak term ``c``); the
    fit assumes the simpler ``dy/dt = -k*y`` (no ``c``), a systematic (not random) mis-specification. The
    driver ``k`` is fit against the first 35 of 50 time points; the remaining 15 are held out. Held-out
    coverage is the fraction of held-out points whose residual against the fitted forward falls inside
    the nominal 90%% band (``z = 1.645`` for alpha=0.1) implied by the effective noise budget alone
    (``scale`` with no discrepancy, ``sqrt(scale**2 + model_error**2)`` once one is supplied).
    """

    K_TRUE = 0.6
    FORCING_BIAS = 0.05
    SIGMA = 0.01
    Y0 = 1.0
    N_FIT = 35
    N_SEEDS = 10
    ALPHA_Z = 1.645  # central 90% band, alpha = 0.1

    @classmethod
    def setUpClass(cls):
        cls.t_full = np.linspace(0, 8, 50)
        cls.t_fit = cls.t_full[: cls.N_FIT]
        cls.y_true_full = _sim(lambda u, tt: -cls.K_TRUE * u - cls.FORCING_BIAS, cls.Y0, cls.t_full)

    def _held_out_coverage(self, model_error):
        z = self.ALPHA_Z
        inside = 0
        total = 0
        for seed in range(self.N_SEEDS):
            rng = np.random.RandomState(seed)
            y_obs_full = self.y_true_full + self.SIGMA * rng.randn(len(self.t_full))
            y_obs_fit = y_obs_full[: self.N_FIT]
            y_obs_heldout = y_obs_full[self.N_FIT :]

            k = free(1, name="k", support="positive")
            kwargs = {} if model_error is None else {"model_error": model_error}
            obs = Differential(
                y_obs_fit,
                drivers=[k],
                y0=self.Y0,
                t_grid=self.t_fit,
                scale=self.SIGMA,
                rhs=lambda u, tt, p, ops: -p.k * u,
                **kwargs,
            )
            km, _ = joint([obs]).fit(how="laplace").posterior("k")

            pred_full = _sim(lambda u, tt, _k=km: -_k * u, self.Y0, self.t_full)
            pred_heldout = pred_full[self.N_FIT :]
            scale_eff = self.SIGMA if model_error is None else np.sqrt(self.SIGMA**2 + model_error**2)
            resid = y_obs_heldout - pred_heldout
            inside += int(np.sum(np.abs(resid) <= z * scale_eff))
            total += resid.size
        return inside / total

    def test_no_discrepancy_undercovers(self):
        coverage = self._held_out_coverage(model_error=None)
        self.assertLess(coverage, 0.7)

    def test_model_error_sized_to_bias_restores_nominal_coverage(self):
        coverage = self._held_out_coverage(model_error=0.08)
        self.assertGreaterEqual(coverage, 0.88)


if __name__ == "__main__":
    unittest.main()
