"""Frozen capability and limitation inventory for mixle-pde's legacy solver kernels.

mixle-pde is the compatibility facade over mixle's legacy PDE/ODE numerical kernels (``fem.py``,
``gas_dynamics.py``, ``geophysics.py``, ``monitoring_design.py``, ``posterior_query.py``,
``geo_observations.py``, and the rest of ``mixle_pde/``). ``mixle_pde.problem_adapter.PDEBackendProfile``
lets a caller declare a capability profile in the *abstract*; this module is the companion fact base --
what the kernels that already exist can *actually* do today, one entry per public top-level module, along
nine axes: method, dimension, cell/grid type, boundary-condition support, differentiability, complex
support, steady/transient status, parallel status, and verification level.

Methodology and honesty notes
------------------------------
* This is a frozen SNAPSHOT of current capability, not a target or a promise. A green test proves the
  linear algebra ran; it is not, by itself, evidence the physics is correct -- ``verification_level``
  records only what the existing test suite checks today, never an independent physical validation.
* ``differentiable`` is a conservative static proxy: True means the module imports ``torch`` for at
  least one primary compute path (an autograd-capable route exists somewhere in it). It is not a
  per-function proof that every symbol in the module is differentiable end to end.
* ``complex_support`` means the module uses a complex dtype or the literal imaginary unit somewhere in
  its primary compute path (frequency-domain / spectral methods, mostly).
* ``parallel_status`` is ``"single_process"`` for every entry: a repo-wide sweep found no ``mpi4py``,
  no ``multiprocessing``, and no ``concurrent.futures``/``joblib`` usage anywhere under ``mixle_pde/``.
  Vectorized NumPy/Torch operations are the only concurrency mixle-pde has today; distributed/MPI
  execution is explicitly future (production-backend) work per the mixle-pde work plan's ADR-3, not
  something this inventory should imply exists.
* Non-solver modules (Bayesian posterior utilities, likelihood models, environmental data loaders,
  infrastructure/glue code) are inventoried too -- ``is_solver=False`` and the PDE-specific axes
  (``dimension``, ``grid_type``, ``boundary_conditions``, ``time_regime``) read ``"not_applicable"``
  for them, rather than being silently omitted, per the "unsupported features are explicit" bar.
* ``public_symbols`` lists every top-level, non-underscore class/function actually defined in the
  module (not merely re-exported elsewhere). ``tests/capability_inventory_test.py`` import-sweeps every
  module in this registry and asserts each listed symbol is real and every module file on disk is
  registered -- the mechanical half of the MP-A1 acceptance criterion. The categorical judgement calls
  (dimension, grid type, BC support, time regime, verification level) are the human-reviewed half,
  derived from each module's own docstrings/boundary-handling code and its associated tests; see the
  PR description for the review method.

Source: notes/mixle-pde-ai-native-multiphysics-work-plan.md section 8, MP-A1.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class SolverProfile:
    """Capability/limitation record for one public ``mixle_pde`` top-level module."""

    module: str
    category: str
    is_solver: bool
    method: str
    dimension: tuple[str, ...]
    grid_type: str
    boundary_conditions: tuple[str, ...]
    differentiable: bool
    complex_support: bool
    time_regime: str
    parallel_status: str
    verification_level: str
    public_symbols: tuple[str, ...]
    limitations: tuple[str, ...] = ()

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        for key in ("dimension", "boundary_conditions", "public_symbols", "limitations"):
            data[key] = list(data[key])
        return data


CAPABILITY_INVENTORY: tuple[SolverProfile, ...] = (
    SolverProfile(
        module="mixle_pde._operator",
        category="fem_pde_core",
        is_solver=False,
        method="Typed contracts for the PDE/ODE forward-model machinery.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("ForwardOperator", "ObserveFn", "ForwardModel", "RhsFn"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.adjoint",
        category="fem_pde_core",
        is_solver=False,
        method="Discrete adjoint sensitivities for the sparse-PDE forward operators (workstream C1).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("torch_adjoint_jacobian", "torch_adjoint_jvp"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.attenuation",
        category="environmental_applied",
        is_solver=False,
        method="Closed-form differentiable absorption / attenuation models for the wave and Helmholtz solvers.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="reference_value_checked",
        public_symbols=(
            "thorp_seawater",
            "francois_garrison_seawater",
            "itu_gaseous_oxygen",
            "itu_gaseous_water_vapour",
            "itu_gaseous",
            "itu_rain_specific",
            "db_per_length_to_nepers",
            "quality_factor",
            "complex_modulus_fraction",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.basin",
        category="environmental_applied",
        is_solver=True,
        method="Petroleum-systems / thermal-history forwards: the conductive geotherm and organic maturation.",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet_surface_temperature", "neumann_basal_heat_flux"),
        differentiable=False,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("geotherm", "easy_ro", "easy_ro_profile"),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.beam",
        category="field_pde_solvers",
        is_solver=True,
        method="Euler-Bernoulli beam: transverse vibration and static deflection of a slender beam (a 1D 4th-order PDE).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet_simply_supported_navier_ends",),
        differentiable=True,
        complex_support=False,
        time_regime="steady_and_transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("EulerBernoulliBeam",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.blocky_priors",
        category="bayesian_field_inference",
        is_solver=False,
        method="Blocky, compact, and structurally anisotropic priors for the exploration inversions (workstream A1).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "minimum_support_weights",
            "total_variation_weights",
            "dip_rotated_gradient_operator",
            "blocky_invert",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.boundaries",
        category="environmental_applied",
        is_solver=False,
        method="Closed-form differentiable boundary / interaction models that make the PE a real waveguide.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=True,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "impedance",
            "critical_grazing_angle",
            "seabed_reflection",
            "bottom_loss_db",
            "surface_reflection",
            "rayleigh_roughness",
            "coherent_roughness_factor",
            "radar_surface_reflection",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.capabilities",
        category="infrastructure",
        is_solver=False,
        method="PDE modeling capability catalog and deterministic readiness checks.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "ModelingCapability",
            "ScenarioResult",
            "VerificationScenario",
            "capability_catalog",
            "get_capability",
            "missing_required_dependencies",
            "readiness_report",
            "verification_scenarios",
            "run_verification_scenario",
            "run_required_modeling_checks",
            "assert_required_modeling",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.climate_downscale",
        category="environmental_applied",
        is_solver=False,
        method="L7 -- regional climate downscaling (statistical + dynamical) and site extremes (work-plan L7).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="reference_value_checked",
        public_symbols=(
            "QuantileMap",
            "DownscaledField",
            "fit_quantile_map",
            "apply_quantile_map",
            "downscaled_return_level",
            "downscale",
            "site_spatial_extremes",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.decision_quantities",
        category="bayesian_field_inference",
        is_solver=False,
        method="Decision-quantity UQ: calibrated Monte Carlo pushforwards of a posterior (work-plan A5, IC-8 surface).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "DerivedQuantity",
            "SampledDerivedQuantity",
            "region_mass",
            "prob_exceed",
            "tonnage_above_cutoff",
            "net_pay",
            "drill_target_prob",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.digital_twin",
        category="environmental_applied",
        is_solver=False,
        method="The digital twin of a physical site: monitoring in, what-ifs out (work-plan workstream P, P3).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("DigitalTwin", "build_twin"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.dispersion",
        category="environmental_applied",
        is_solver=True,
        method="Air-quality / dust dispersion, source apportionment, and occupational exposure (workstream G/K).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet", "neumann", "robin", "periodic", "absorbing/PML"),
        differentiable=False,
        complex_support=False,
        time_regime="steady_and_transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "DispersionOperator",
            "Mesh",
            "SourceTerm",
            "VentilationBC",
            "ConcentrationField",
            "gaussian_plume",
            "apportion_sources",
            "occupational_exposure",
        ),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.dynamics",
        category="fem_pde_core",
        is_solver=True,
        method="Pluggable spatial dynamics operators for PDE-constrained models (method-of-lines).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet", "neumann", "periodic"),
        differentiable=False,
        complex_support=True,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "DynamicsOperator",
            "DiffusionOperator",
            "AdvectionOperator",
            "AdvectionDiffusionOperator",
            "laplacian_matrix",
            "upwind_gradient_matrix",
            "register_dynamics_operator",
            "available_dynamics_operators",
            "make_operator",
            "integrate_adaptive",
            "integrate_stiff",
            "integrate_sensitivity",
            "integrate_dae",
            "burgers_rhs",
            "kdv_rhs",
            "shallow_water_rhs",
            "conservation_law_rhs",
            "spectral_derivative",
            "black_scholes_rhs",
            "lane_emden_rhs",
        ),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.earth_scenarios",
        category="geophysics_forward_inverse",
        is_solver=False,
        method="Reusable synthetic 3D/4D Earth inversion harnesses.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "Synthetic3DInversionResult",
            "Synthetic4DAssimilationResult",
            "run_synthetic_3d_geochem_geophysics_inversion",
            "run_synthetic_4d_biostrat_assimilation",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.elastic",
        category="field_pde_solvers",
        is_solver=True,
        method="3D isotropic elastodynamic wave equation on a staggered grid, explicit velocity-stress leapfrog.",
        dimension=("3D",),
        grid_type="staggered structured grid (Yee / velocity-stress staggered)",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("ElasticWave3D",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.elastic_aniso",
        category="field_pde_solvers",
        is_solver=True,
        method="3D anisotropic (VTI / TTI) elastodynamic wave equation on a staggered velocity-stress grid.",
        dimension=("3D",),
        grid_type="staggered structured grid (Yee / velocity-stress staggered)",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "AnisotropicElasticWave3D",
            "thomsen_to_cij",
            "vti_voigt_matrix",
            "bond_matrix",
            "rotate_voigt",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.electrostatics",
        category="field_pde_solvers",
        is_solver=True,
        method="Poisson-Boltzmann electrostatics for biomolecular / continuum-solvent problems.",
        dimension=("2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet",),
        differentiable=True,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "linearized_pbe",
            "nonlinear_pbe",
            "reaction_field_energy",
            "yukawa_potential",
            "born_solvation_energy",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.em_diffusion",
        category="field_pde_solvers",
        is_solver=True,
        method="Diffusive / quasi-static electromagnetic forwards for the conductive earth (CSEM / MT / AEM, eddy-current NDE).",
        dimension=("1D", "2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet",),
        differentiable=True,
        complex_support=True,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("layered_mt_impedance", "assemble_mt_te", "mt_2d_te"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.em_diffusion_3d",
        category="field_pde_solvers",
        is_solver=True,
        method="3-D diffusive / quasi-static curl-curl electromagnetics on a staggered Yee edge grid (CSEM / MT / AEM).",
        dimension=("2D", "3D"),
        grid_type="staggered structured grid (Yee / velocity-stress staggered)",
        boundary_conditions=("dirichlet",),
        differentiable=True,
        complex_support=True,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("assemble_curl_curl_3d", "mt_3d", "csem_3d"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.env_data",
        category="environmental_applied",
        is_solver=False,
        method="Ocean/atmosphere environmental-medium assembler: real-world profiles/rasters onto the (nz, nr) coefficient",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "assemble_field",
            "seabed_mask",
            "apply_mask",
            "load_gebco",
            "load_woa_argo",
            "load_dem",
            "load_era5_profile",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.exposure_pathways",
        category="environmental_applied",
        is_solver=False,
        method="Community exposure pathways: sampling transport fields at receptor locations (workstream K2).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("ConcentrationField", "ReceptorExposure", "receptor_exposure", "couple_pathways"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.fem",
        category="fem_pde_core",
        is_solver=True,
        method="Unstructured finite elements: P1 (linear triangular) FEM for the Poisson equation.",
        dimension=("2D", "3D", "4D"),
        grid_type="unstructured simplex (triangular/tetrahedral) mesh",
        boundary_conditions=("dirichlet",),
        differentiable=False,
        complex_support=False,
        time_regime="steady_and_transient",
        parallel_status="single_process",
        verification_level="manufactured_solution_checked",
        public_symbols=(
            "boundary_nodes",
            "simplex_p1_gradients",
            "assemble_simplex_stiffness_matrix",
            "assemble_simplex_mass_matrix",
            "assemble_simplex_fem_matrices",
            "assemble_simplex_load_vector",
            "solve_simplex_poisson",
            "step_simplex_diffusion",
            "simulate_simplex_diffusion",
            "fem_poisson",
        ),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.field_assimilation",
        category="bayesian_field_inference",
        is_solver=False,
        method="4D assimilation and smoothing of an evolving latent field (workstream G7).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "PosteriorField4D",
            "PosteriorFieldSamples4D",
            "ParticleAssimilationReport",
            "gaspari_cohn_localization",
            "assimilate_4d",
            "assimilate_4d_linear_dynamics",
            "assimilate_4d_joint_linear_dynamics",
            "particle_assimilate_4d",
            "assimilate_4d_ensemble",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.field_gauss_newton",
        category="bayesian_field_inference",
        is_solver=False,
        method="Gauss-Newton inversion for BOUNDED (nonlinear-transform) latent fields (workstream G6, ladder rung 2).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("GaussNewtonReport", "gauss_newton_invert", "gauss_newton_hessian_hvp"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.field_inversion",
        category="bayesian_field_inference",
        is_solver=False,
        method="Linear-Gaussian inversion of a latent 3D field from multimodal observations (workstream G6, core).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "FieldGaussianPrior",
            "PosteriorPredictiveCheck",
            "linear_gaussian_invert",
            "sparse_linear_gaussian_invert",
            "posterior_predictive_check",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.field_mcmc",
        category="bayesian_field_inference",
        is_solver=False,
        method="Small-reference MCMC inversion for latent 3D fields.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "MCMCReport",
            "field_log_posterior_kernel",
            "metropolis_field_invert",
            "field_log_posterior_grad_kernel",
            "pcn_field_invert",
            "mala_field_invert",
            "hmc_field_invert",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.field_priors",
        category="bayesian_field_inference",
        is_solver=False,
        method="Depth weighting, spatiotemporal, and cross-property coupling priors (workstream G5, remaining rungs).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="reference_value_checked",
        public_symbols=(
            "SpatioTemporalGaussianPrior",
            "CrossPropertyPrior",
            "FaciesMixturePrior",
            "TVFieldPrior",
            "MinimumSupportPrior",
            "depth_weights",
            "depth_weighted_marginal_precision",
            "depth_weighted_marginal_precision_sparse",
            "joint_linear_gaussian_invert",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.flow",
        category="fluid_flow",
        is_solver=True,
        method="2D incompressible Navier-Stokes for flow inverse problems (phase 5).",
        dimension=("2D", "3D"),
        grid_type="structured regular (Cartesian) finite-difference/finite-volume grid",
        boundary_conditions=("dirichlet_no_slip_walls",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("NavierStokes2D",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.flow3d",
        category="fluid_flow",
        is_solver=True,
        method="3D incompressible Navier-Stokes by Chorin projection (phase 5, the 3-D frontier of ``flow.py``).",
        dimension=("2D", "3D"),
        grid_type="structured regular (Cartesian) finite-difference/finite-volume grid",
        boundary_conditions=("dirichlet_no_slip_walls",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("NavierStokes3D",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.gas_dynamics",
        category="gas_dynamics",
        is_solver=True,
        method="Compressible gas dynamics -- the 1-D Euler equations with an exact Riemann solver.",
        dimension=("1D",),
        grid_type="structured 1D finite-volume grid",
        boundary_conditions=("outflow_zero_gradient",),
        differentiable=False,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "CombustionResult",
            "exact_riemann_solution",
            "solve_euler_1d",
            "solve_reactive_euler_1d",
            "engine_cylinder_volume",
            "simulate_zero_d_combustion",
        ),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.geo_observations",
        category="bayesian_field_inference",
        is_solver=False,
        method="Geochemistry and paleontology/biostratigraphy observation models (workstream G3).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "GeochemAssay",
            "MultiElementAssay",
            "BiostratConstraint",
            "FossilAssemblage",
            "GeochronologyAge",
            "StratigraphicCorrelation",
            "FaciesIntervalConstraint",
            "assay_log_likelihood",
            "multi_element_assay_log_likelihood",
            "additive_log_ratio",
            "inverse_additive_log_ratio",
            "biostrat_log_likelihood",
            "fossil_assemblage_log_likelihood",
            "geochronology_log_likelihood",
            "stratigraphic_correlation_log_likelihood",
            "facies_interval_log_likelihood",
            "assay_posterior_predictive",
            "multi_element_assay_posterior_predictive",
            "fossil_assemblage_posterior_predictive",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.geometry_to_mesh",
        category="fem_pde_core",
        is_solver=False,
        method="Survey-geometry -> mesh mapping (workstream B7, IC-4 `SurveyGeometry`).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="reference_value_checked",
        public_symbols=("nearest_node_indices", "electrodes_to_schedule", "yee_edge_index"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.geophysics",
        category="geophysics_forward_inverse",
        is_solver=True,
        method="Near-surface geophysical forward operators and a regularized inversion engine.",
        dimension=("2D", "3D"),
        grid_type="structured regular grid / point-sensor sensitivity kernel",
        boundary_conditions=("dirichlet", "absorbing/PML"),
        differentiable=True,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "JointInversionResult",
            "field_direction",
            "magnetic_dipole_sensitivity",
            "gravity_point_sensitivity",
            "gravity_prism_sensitivity",
            "magnetic_prism_sensitivity",
            "depth_weighting",
            "depth_weighted_roughness",
            "dc_resistivity",
            "straight_ray_operator",
            "eikonal_traveltime",
            "traveltime_tomography",
            "roughness_operator",
            "regularized_gauss_newton",
            "invert_potential_field",
            "cross_gradient",
            "joint_inversion",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.groundwater",
        category="fluid_flow",
        is_solver=True,
        method="Groundwater flow, reactive solute transport, and contaminant source inversion (workstream G).",
        dimension=("dimension_agnostic",),
        grid_type="structured regular (Cartesian) finite-difference/finite-volume grid",
        boundary_conditions=("dirichlet", "neumann"),
        differentiable=False,
        complex_support=False,
        time_regime="steady_and_transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "GroundwaterTransportOperator",
            "SourceRecalibration",
            "HeldOutPrediction",
            "SourcePosterior",
            "darcy_velocity",
            "ogata_banks_plume",
            "simulate_wells",
            "invert_source",
        ),
        limitations=(
            "dimension-agnostic: the module accepts an arbitrary caller-supplied shape/operator rather than fixing a spatial dimension itself",
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.guided_wave",
        category="field_pde_solvers",
        is_solver=True,
        method="Semi-analytical finite element (SAFE) guided-wave dispersion for an isotropic plate (Lamb + SH modes).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("implicit_traction_free_surfaces",),
        differentiable=False,
        complex_support=True,
        time_regime="eigenvalue",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("DispersionCurves", "SAFEPlate", "safe_dispersion"),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.heat",
        category="field_pde_solvers",
        is_solver=True,
        method="Transient heterogeneous heat conduction for active thermography and conduction inverse problems.",
        dimension=("1D", "2D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet", "neumann", "periodic"),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("TransientHeat",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.helmholtz_pml",
        category="field_pde_solvers",
        is_solver=True,
        method="Frequency-domain Helmholtz with a perfectly-matched-layer boundary and complex (attenuating) modulus.",
        dimension=("1D", "2D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet", "absorbing/PML"),
        differentiable=True,
        complex_support=True,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("pml_profile", "helmholtz_pml_operator", "solve_helmholtz_pml"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.induced_polarization",
        category="field_pde_solvers",
        is_solver=True,
        method="Spectral induced polarization (SIP) forward for disseminated-sulphide mineral exploration.",
        dimension=("2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet",),
        differentiable=True,
        complex_support=True,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("cole_cole_conductivity", "sip_forward", "apparent_conductivity", "geometric_factor"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.informativeness",
        category="bayesian_field_inference",
        is_solver=False,
        method="Data-informativeness diagnostic: does the posterior reflect the data, or just the prior?",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "prior_marginal_variance",
            "variance_reduction",
            "prior_dominated_mask",
            "region_prior_dominated",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.inverse",
        category="fem_pde_core",
        is_solver=False,
        method="Differential-equation forward models for Bayesian inverse problems.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("Differential",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.latent",
        category="bayesian_field_inference",
        is_solver=False,
        method="Latent 3D/4D field objects and posterior artifacts (workstream G1, first card).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "SparsePosteriorPrecision",
            "Field3D",
            "Field4D",
            "PosteriorField3D",
            "PosteriorFieldSamples3D",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.linear_solve",
        category="fem_pde_core",
        is_solver=False,
        method="Iterative sparse solvers + factorization caching for survey-scale linear-Gaussian inversion (C3).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("make_factor_cache", "spd_solve", "marginal_std_cg", "dense_spd_solve"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.material_transport",
        category="fluid_flow",
        is_solver=True,
        method="1-D lumped material-transport physics for mineral-processing plant design (slurry / conveyor / floc).",
        dimension=("1D", "2D"),
        grid_type="structured regular (Cartesian) finite-difference/finite-volume grid",
        boundary_conditions=("absorbing/PML",),
        differentiable=False,
        complex_support=False,
        time_regime="steady_and_transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("slurry_pressure_drop", "conveyor_throughput", "flocculation_kinetics"),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.maxwell",
        category="field_pde_solvers",
        is_solver=True,
        method="3-D source-free Maxwell curl equations on a Yee (staggered) grid, explicit leapfrog (FDTD).",
        dimension=("3D",),
        grid_type="staggered structured grid (Yee / velocity-stress staggered)",
        boundary_conditions=("dirichlet_pec_walls",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("Maxwell3D",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.mesh",
        category="fem_pde_core",
        is_solver=True,
        method="Simplex mesh generation and deformation helpers for PDE models.",
        dimension=("1D", "2D", "3D", "4D"),
        grid_type="unstructured simplex (triangular/tetrahedral) mesh",
        boundary_conditions=("absorbing/PML",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="manufactured_solution_checked",
        public_symbols=(
            "SimplexMesh",
            "MovingSimplexMesh",
            "box_simplex_mesh",
            "telescoping_mesh",
            "delaunay_mesh",
            "moving_mesh",
            "pipe_simplex_mesh",
            "pipe_boundary_nodes",
            "pipe_boundary_facets",
            "refine_simplex_mesh",
            "interpolate_simplex_field",
            "pipe_radial_deformation",
            "space_time_mesh",
        ),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.migration",
        category="field_pde_solvers",
        is_solver=True,
        method="Reverse-time migration (RTM) imaging on the differentiable acoustic wave stepper.",
        dimension=("2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "model_data",
            "rtm_image",
            "born_modeling",
            "lsrtm_step",
            "model_data_3d",
            "rtm_image_3d",
            "elastic_rtm_2d",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.misfit",
        category="bayesian_field_inference",
        is_solver=False,
        method="Cycle-skip-robust FWI misfit functionals: differentiable objectives that replace the plain L2 residual for",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=True,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "hilbert_envelope",
            "envelope_misfit",
            "xcorr_traveltime_misfit",
            "wasserstein1d_misfit",
            "l2_misfit",
            "misfit",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.model_error",
        category="bayesian_field_inference",
        is_solver=False,
        method="Model-error (theory-error) discrepancy covariance for likelihoods that assume a perfect forward model.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("diagonal_discrepancy", "inflated_noise_cov"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.model_selection",
        category="bayesian_field_inference",
        is_solver=False,
        method="Bayesian model selection over competing subsurface hypotheses (workstream C8).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("InversionResult", "log_evidence_laplace", "bayes_factor", "rank_hypotheses"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.monitoring_design",
        category="bayesian_field_inference",
        is_solver=False,
        method="G6 -- monitoring-network design / sensor placement (work-plan workstream G).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("GaussianSourcePosterior", "design_monitoring_network", "expected_detection_time"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.multiphysics",
        category="fem_pde_core",
        is_solver=True,
        method="Multiphysics forward solvers: nD steady diffusion/Poisson and coupled PDE systems.",
        dimension=("1D", "2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet",),
        differentiable=False,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="manufactured_solution_checked",
        public_symbols=("CoupledPDESystem", "solve_poisson", "solve_elasticity", "run_coupled"),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.nonlinear",
        category="fem_pde_core",
        is_solver=True,
        method="Differentiable nonlinear steady solver: Newton for ``F(u; theta) = 0`` with an implicit-function-theorem",
        dimension=("dimension_agnostic",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet",),
        differentiable=True,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="manufactured_solution_checked",
        public_symbols=("nonlinear_solve", "reaction_diffusion_residual"),
        limitations=(
            "dimension-agnostic: the module accepts an arbitrary caller-supplied shape/operator rather than fixing a spatial dimension itself",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.normal_modes",
        category="field_pde_solvers",
        is_solver=True,
        method="KRAKEN-style depth normal-mode solver for a horizontally-stratified ocean waveguide.",
        dimension=("1D",),
        grid_type="1D layered/stratified column",
        boundary_conditions=("dirichlet", "robin"),
        differentiable=True,
        complex_support=True,
        time_regime="eigenvalue",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("ModeSet", "NormalModes1D", "pekeris_characteristic", "pekeris_mode_count"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.observations",
        category="geophysics_forward_inverse",
        is_solver=False,
        method="Typed observations and a common likelihood interface over 3D/4D latent fields (workstream G2).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "Observation",
            "SurveyGeometry",
            "ForwardOperator",
            "ForwardOperatorRegistry",
            "gaussian_log_likelihood",
            "gravity_forward_operator",
            "magnetics_forward_operator",
            "borehole_forward_operator",
            "dc_resistivity_forward_operator",
            "layered_mt_forward_operator",
            "aem_layered_forward_operator",
            "mt_2d_te_forward_operator",
            "mt_3d_forward_operator",
            "csem_3d_forward_operator",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.ops",
        category="fem_pde_core",
        is_solver=False,
        method="The math namespace handed to differential forward models, so user callbacks never import a backend.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("make_ops",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.parabolic_equation",
        category="field_pde_solvers",
        is_solver=True,
        method="Range-marched split-step Fourier parabolic-equation propagator (Tappert standard PE).",
        dimension=("2D",),
        grid_type="periodic pseudo-spectral grid (FFT-based)",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=True,
        time_regime="range_marched",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("ParabolicEquation2D", "modified_refractivity_index", "lloyd_mirror_pressure"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.pde",
        category="fem_pde_core",
        is_solver=True,
        method="PDE-constrained state-space models for mixle.ppl (multivariate Kalman/RTS + EM).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("neumann",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "PDEStateSpaceResult",
            "kalman_rts_em",
            "pde_fit",
            "fit_diffusivity",
            "fit_pde_parameters",
            "fit_reaction_diffusion",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.pde_solve",
        category="fem_pde_core",
        is_solver=True,
        method="Adjoint-capable sparse PDE solves for large-scale inverse problems.",
        dimension=("2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet", "absorbing/PML"),
        differentiable=True,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("sparse_used_since", "sparse_solve", "divergence_form", "laplacian", "helmholtz_operator"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.petrophysics",
        category="environmental_applied",
        is_solver=False,
        method="Closed-form petrophysical transforms over well-log curves (workstream B3).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("vp_from_dt", "gardner_density", "archie_sw"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.plate",
        category="field_pde_solvers",
        is_solver=True,
        method="Kirchhoff-Love thin-plate bending, static and dynamic, on a rectangular grid.",
        dimension=("2D",),
        grid_type="structured rectangular grid",
        boundary_conditions=("dirichlet_simply_supported_navier_edges",),
        differentiable=True,
        complex_support=False,
        time_regime="steady_and_transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("KirchhoffPlate",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.pnp",
        category="field_pde_solvers",
        is_solver=True,
        method="Poisson-Nernst-Planck coupled electro-diffusion for ion channels and nanopores (1-D, equilibrium).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("dirichlet", "absorbing/PML"),
        differentiable=True,
        complex_support=False,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("debye_length", "pnp_equilibrium"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.poroelastic",
        category="field_pde_solvers",
        is_solver=True,
        method="1D Biot poroelastic wave equation on a staggered grid, explicit velocity-stress leapfrog.",
        dimension=("1D",),
        grid_type="staggered structured grid (Yee / velocity-stress staggered)",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "BiotPoroelastic1D",
            "DeformationPosterior",
            "gassmann_moduli",
            "biot_gassmann_velocity",
            "poroelastic_subsidence",
            "invert_deformation",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.posterior_calibration",
        category="bayesian_field_inference",
        is_solver=False,
        method="Posterior calibration diagnostics for latent field artifacts.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "TruthCoverage",
            "HeldoutFit",
            "UncertaintyInflation",
            "IdentifiabilityDiagnostic",
            "Recalibration",
            "truth_coverage",
            "heldout_observation_check",
            "observation_sensitivity",
            "uncertainty_inflation",
            "identifiability_diagnostic",
            "variance_inflation_factor",
            "split_conformal_quantile",
            "recalibrate",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.posterior_query",
        category="bayesian_field_inference",
        is_solver=False,
        method="Posterior extraction and compact storage for latent-field posteriors (workstream G8).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "MarginalSummary",
            "MarginalTimeSeries",
            "DerivedTimeSeries",
            "DerivedQuantity",
            "SampledDerivedQuantity",
            "PosteriorEnsemble",
            "marginal_at_points",
            "section",
            "time_slice",
            "region_summary",
            "marginal_time_series",
            "region_time_summary",
            "derived_quantity",
            "derived_quantity_physical",
            "sampled_derived_quantity",
            "region_mass",
            "region_mass_time_series",
            "compress_to_low_rank",
            "to_diagonal",
            "to_ensemble",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.potential_fields",
        category="geophysics_forward_inverse",
        is_solver=False,
        method="Full-tensor gravity gradiometry (FTG) and vector/gradient magnetic sensitivity kernels.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "gravity_gradient_components",
            "gravity_gradient_tensor",
            "trace_free_zz",
            "magnetic_vector_sensitivity",
            "magnetic_gradient_tensor",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.problem_adapter",
        category="infrastructure",
        is_solver=False,
        method="Capability negotiation for solver-neutral mathematical PDE problems.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "PDEBackendProfile",
            "PDECompatibilityReport",
            "UnsupportedPDEProblem",
            "inspect_math_problem",
            "require_compatible",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.propagation_inverse",
        category="environmental_applied",
        is_solver=False,
        method="Convenience builders that pose the sonar/radar propagation INVERSE problems on the PE forward.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("refractivity_from_clutter", "ocean_sound_speed_inversion"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.ray_scattering",
        category="environmental_applied",
        is_solver=False,
        method="High-frequency (asymptotic) EM/acoustic scattering: PO radar cross section, ray multipath, edge diffraction.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=True,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "wavelength",
            "po_rcs",
            "fresnel_integral",
            "knife_edge_diffraction",
            "two_ray_pattern",
            "multipath_power",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.reactive_transport",
        category="fluid_flow",
        is_solver=True,
        method="Tailings seepage + acid-mine-drainage (AMD) reactive transport (workstream G5).",
        dimension=("dimension_agnostic",),
        grid_type="structured regular (Cartesian) finite-difference/finite-volume grid",
        boundary_conditions=("dirichlet", "neumann"),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "ReactiveTransport",
            "ph_from_concentration",
            "amd_reaction",
            "amd_reactions_step",
            "effluent_assay",
            "effluent_log_likelihood",
        ),
        limitations=(
            "dimension-agnostic: the module accepts an arbitrary caller-supplied shape/operator rather than fixing a spatial dimension itself",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.reasoning",
        category="bayesian_field_inference",
        is_solver=False,
        method="Cross-modal subsurface reasoning: fuse geophysical modalities into a belief with UQ.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=(
            "JointPotentialField",
            "SpatialFieldStore",
            "MechanisticFieldReasoner",
            "field_describer",
            "describe_posterior",
        ),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.reclamation",
        category="environmental_applied",
        is_solver=False,
        method="G9 -- environmental constraints feed production + reclamation planning (work-plan workstream G).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("BlockFieldPosterior", "exclusion_mask", "reclamation_cost", "apply_env_constraints"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.reductions",
        category="geophysics_forward_inverse",
        is_solver=False,
        method="Frequency-domain reductions for a loaded potential-field grid (workstream B4).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("reduce_to_pole", "upward_continue"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.refractivity",
        category="environmental_applied",
        is_solver=False,
        method="Atmospheric radio refractivity as closed-form differentiable transforms for radar tropospheric propagation.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "refractivity",
            "saturation_vapour_pressure",
            "vapour_pressure_from_humidity",
            "modified_refractivity",
            "standard_refractivity_profile",
            "duct_layers",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.rock_physics",
        category="environmental_applied",
        is_solver=False,
        method="Biot-Gassmann fluid substitution as closed-form differentiable rock-physics transforms.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "gassmann_ksat",
            "gassmann_kdry",
            "moduli_from_velocity",
            "velocity_from_moduli",
            "fluid_substitute",
            "fluid_substitute_uncertain",
            "fluid_modulus_sensitivity",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.sample_update",
        category="bayesian_field_inference",
        is_solver=False,
        method="Importance updates for sampled 3D/4D field posteriors.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "SampleUpdateReport",
            "geochem_assay_likelihood",
            "biostrat_constraint_likelihood",
            "geochronology_age_likelihood",
            "stratigraphic_correlation_likelihood",
            "facies_interval_likelihood",
            "timed_likelihood",
            "update_sampled_field_posterior",
            "update_sampled_field_posterior_with_observations",
            "update_sampled_field_posterior_4d",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.schrodinger",
        category="field_pde_solvers",
        is_solver=True,
        method="Time-dependent Schrodinger equation -- the split-step Fourier (Strang) propagator.",
        dimension=("1D", "2D", "3D"),
        grid_type="periodic pseudo-spectral grid (FFT-based)",
        boundary_conditions=("periodic",),
        differentiable=False,
        complex_support=True,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="manufactured_solution_checked",
        public_symbols=("schrodinger_split_step", "probability_density", "norm"),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.seismic_processing",
        category="environmental_applied",
        is_solver=False,
        method="Single-gather seismic processing and well-to-seismic calibration.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="manufactured_solution_checked",
        public_symbols=("nmo_correction", "stack", "well_tie"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.sensitivity_compress",
        category="bayesian_field_inference",
        is_solver=False,
        method="Wavelet-thresholded sensitivity-matrix compression for large potential-field surveys (C4).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("wavelet_compress",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.shape",
        category="environmental_applied",
        is_solver=False,
        method="Geometry by level sets: shape optimization and inverse shape inference (phase 3).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("level_set_material", "shape_optimize"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.simulation_service",
        category="infrastructure",
        is_solver=False,
        method="IC-11 -- scenario & forward-simulation runner (work-plan workstream P).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "ScenarioStep",
            "Scenario",
            "SimResult",
            "register_forward",
            "available_forwards",
            "write_result_artifact",
            "read_result_artifact",
            "read_result_header",
            "simulate",
            "get_tool_catalog",
            "register_surrogate",
            "propagate_uq",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.smoluchowski",
        category="environmental_applied",
        is_solver=False,
        method="Steady Smoluchowski diffusion-limited association rates for protein/ligand binding.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=(
            "smoluchowski_rate_radial",
            "smoluchowski_rate_box",
            "smoluchowski_debye_factor",
            "smoluchowski_rate_free",
        ),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.sound_speed",
        category="environmental_applied",
        is_solver=False,
        method="Ocean sound-speed as closed-form differentiable transforms c(T, S, D) -- the acoustic refractive driver.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="reference_value_checked",
        public_symbols=("mackenzie", "unesco", "depth_to_pressure", "pressure_to_depth"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.spectral_flow",
        category="fluid_flow",
        is_solver=True,
        method="Pseudo-spectral incompressible Navier-Stokes (2-D and 3-D, with an optional Smagorinsky LES closure).",
        dimension=("2D", "3D"),
        grid_type="periodic pseudo-spectral grid (FFT-based)",
        boundary_conditions=("periodic",),
        differentiable=False,
        complex_support=True,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("incompressible_ns_spectral", "incompressible_boussinesq_spectral", "kinetic_energy"),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
    SolverProfile(
        module="mixle_pde.surrogate",
        category="infrastructure",
        is_solver=False,
        method="E6 -- physics-surrogate distillation + cascade.",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=True,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("Surrogate", "distill_forward", "to_task_cascade_adapter"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.tools",
        category="infrastructure",
        is_solver=False,
        method="IC-3 -- physics tool JSON-schemas and handlers (work-plan E4). The model-callable surface over the",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("run_inversion", "query_posterior", "gassmann", "forward_model"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.two_phase",
        category="fluid_flow",
        is_solver=True,
        method="2D immiscible two-fluid incompressible Navier-Stokes by a diffuse-interface (phase-field) projection.",
        dimension=("2D",),
        grid_type="structured regular (Cartesian) finite-difference/finite-volume grid",
        boundary_conditions=("dirichlet", "periodic"),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("TwoPhaseFlow2D", "ops_clamp"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.uq_lowrank",
        category="bayesian_field_inference",
        is_solver=False,
        method="Matrix-free / low-rank Hessian UQ + selected inversion (workstream C2, inversion realism & scale).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("randomized_lowrank_hessian", "takahashi_selected_inversion"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.viscoelastic",
        category="field_pde_solvers",
        is_solver=True,
        method="1D time-domain constant-Q viscoacoustic wave solver (GSLS memory-variable formulation).",
        dimension=("1D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("ViscoacousticWave1D", "tau_fit", "q_of_omega"),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.voi",
        category="bayesian_field_inference",
        is_solver=False,
        method="Value-of-information: a linearized pre-posterior variance-reduction proxy (workstream C8).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("expected_variance_reduction", "next_best_observation"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.water_balance",
        category="environmental_applied",
        is_solver=False,
        method="L2 -- physical climate risk to operations: catchment water balance (work-plan L2).",
        dimension=("not_applicable",),
        grid_type="not_applicable",
        boundary_conditions=("not_applicable",),
        differentiable=False,
        complex_support=False,
        time_regime="not_applicable",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("WaterBudget", "water_balance"),
        limitations=(
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.wave",
        category="field_pde_solvers",
        is_solver=True,
        method="2D acoustic wave equation for full-waveform-inversion-style inverse problems (phase 2 completion).",
        dimension=("2D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("WaveEquation2D",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.wave3d",
        category="field_pde_solvers",
        is_solver=True,
        method="3D acoustic wave equation for volumetric full-waveform-inversion-style inverse problems.",
        dimension=("2D", "3D"),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("absorbing/PML",),
        differentiable=True,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("WaveEquation3D",),
        limitations=("single-process only: no MPI, multiprocessing, or distributed execution path",),
    ),
    SolverProfile(
        module="mixle_pde.wave_pml",
        category="field_pde_solvers",
        is_solver=True,
        method="2-D acoustic wave propagation with a perfectly-matched-layer (PML) absorbing boundary.",
        dimension=("2D",),
        grid_type="structured regular finite-difference grid",
        boundary_conditions=("absorbing/PML",),
        differentiable=False,
        complex_support=False,
        time_regime="transient",
        parallel_status="single_process",
        verification_level="unit_tested_only",
        public_symbols=("solve_wave_pml",),
        limitations=(
            "no torch-backed autograd path detected; gradients (if needed) require external finite differences",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
            "covered by unit tests only; no analytic, manufactured-solution, or external reference check is recorded against it",
        ),
    ),
    SolverProfile(
        module="mixle_pde.wavenumber_integration",
        category="field_pde_solvers",
        is_solver=True,
        method="Full-wave field in a horizontally-stratified medium by wavenumber integration (the Fast-Field method).",
        dimension=("1D", "3D"),
        grid_type="1D layered/stratified column",
        boundary_conditions=("none_modeled",),
        differentiable=True,
        complex_support=True,
        time_regime="steady",
        parallel_status="single_process",
        verification_level="analytic_reference_checked",
        public_symbols=("WavenumberIntegration1D",),
        limitations=(
            "no explicit boundary-condition machinery modeled for this module; callers handle domain truncation/BCs externally",
            "single-process only: no MPI, multiprocessing, or distributed execution path",
        ),
    ),
)


_BY_MODULE: dict[str, SolverProfile] = {profile.module: profile for profile in CAPABILITY_INVENTORY}

if len(_BY_MODULE) != len(CAPABILITY_INVENTORY):
    raise AssertionError("duplicate module entries in CAPABILITY_INVENTORY")


def get_profile(module: str) -> SolverProfile:
    """Look up a profile by its fully-qualified module name, e.g. ``"mixle_pde.fem"``."""
    try:
        return _BY_MODULE[module]
    except KeyError as exc:
        raise KeyError(f"no capability_inventory entry for module {module!r}") from exc


def modules() -> tuple[str, ...]:
    """Every module name registered in the inventory, in registry order."""
    return tuple(profile.module for profile in CAPABILITY_INVENTORY)


def solver_profiles() -> tuple[SolverProfile, ...]:
    """Only the entries that are themselves discretized PDE/ODE solvers (``is_solver=True``)."""
    return tuple(profile for profile in CAPABILITY_INVENTORY if profile.is_solver)


def by_category() -> dict[str, tuple[SolverProfile, ...]]:
    """Group registered profiles by their ``category`` label."""
    grouped: dict[str, list[SolverProfile]] = {}
    for profile in CAPABILITY_INVENTORY:
        grouped.setdefault(profile.category, []).append(profile)
    return {category: tuple(profiles) for category, profiles in grouped.items()}


def to_capability_matrix() -> dict[str, Any]:
    """Machine-readable dict form -- the exact shape serialized to ``docs/capability-matrix.json``."""
    return {
        "schema_version": 1,
        "source": "mixle_pde.verification.capability_inventory.CAPABILITY_INVENTORY",
        "modules": [profile.as_dict() for profile in CAPABILITY_INVENTORY],
    }


def write_capability_matrix(path: str | Path) -> Path:
    """Write the current inventory to ``path`` as byte-stable, sorted-key JSON. Returns the path written."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(to_capability_matrix(), indent=2, sort_keys=True) + "\n"
    target.write_text(payload)
    return target
